// Generated by scripts/fetch-fomo-stats.js — refreshed weekly via
// .github/workflows/refresh-fomo-stats.yml. Committed to the repo (not
// gitignored) so the site always has a value to build with, even on a
// fresh clone between refresh runs.
import stats from "../../scripts/fomo-stats.json";

export interface FomoStats {
  source: string;
  sourceUrl: string;
  fetchedAt: string;
  fees30d: { raw: number; formatted: string };
  dexVolume30d: { raw: number; formatted: string };
}

export const FOMO_STATS: FomoStats = stats;
